### ISSUE TITLE
fix apiResources (apiAccess) if broken

### ISSUE THREAD

**Issue by allan-walpy** [allan-walpy/vulmy#76]
briefly: non root user can't use api call (even if them have same or above api resource)
i.e. apiResource "/" - Ok, "smth.smth/info.version" or "smth.smth/info" - excpected Ok, actual Forbidden; 

some useless logs on issue:
```log
Starting test execution, please wait...
Hosting environment: Production
Content root path: /home/walpy/git/vulmy/out/Debug/server/netcoreapp2.2
Now listening on: http://[::]:4000
Application started. Press Ctrl+C to shut down.
requesst = 
-----response----:
returned: Forbidden
headers: 
-----header----:

Date=Fri, 14 Dec 2018 17:23:51 GMT
Server=Kestrel
-----header-end-----

content: 
-----content----:

----content-end-----


-----response-end-----


Application is shutting down...
Failed   Vulmy.Test.Integration.ApiInfoTimeTest.Test_Info_Time_As_Valid_Up
Error Message:
 Assert.Equal() Failure
Expected: OK
Actual:   Forbidden
Stack Trace:
   at Vulmy.Test.Integration.ApiTest.Assert_StatusCode_Is(HttpResponseMessage response, HttpStatusCode code) in /home/walpy/git/vulmy/src/Test/Integration/ApiTest.Asserts.cs:line 12
   at Vulmy.Test.Integration.ApiInfoTimeTest.Test_Info_Time_As_Valid(LoginRequest user, HttpStatusCode excpectedCode, Dictionary`2 excpectedHeaders) in /home/walpy/git/vulmy/src/Test/Integration/ApiInfoTimeTest.cs:line 36
Results File: /home/walpy/git/vulmy/out/test-explorer/0.trx

Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
Test execution time: 31.9677 Seconds

Process 1296 finished
```

**Comment by allan-walpy** [comment]
can reproduce on working app in debug/production configuration

**Comment by allan-walpy** [comment]
all apiResources start with `.` - and functioning properly
